### ISSUE TITLE
Shop Plugin Issue

### ISSUE THREAD

**Issue by Waater** [HmmHmmmm/ShopPlugin#2]
So I opened up the plugin and created a category correctly. I did /shop it shows a chest then immediately closes it.

**Comment by HmmHmmmm** [comment]
@xXWaterFrogzX Enough have pictures or videos silk, I don't understand.

**Comment by Adam1609** [comment]
@HmmHmmmm what he means is that when you create a category, open the category again will cause the menu to close itself

**Comment by HmmHmmmm** [comment]
@Adam1609 Thank you for explaining
@xXWaterFrogzX I check already, Not as said, If you don't understand, watch the clip https://youtu.be/Rd7uGpD1tIU

**Comment by Waater** [comment]
Ok I will record it once I get home

**Comment by Waater** [comment]
https://www.youtube.com/watch?v=gbdXcTH-_dw this video shows the bug properly

**Comment by HmmHmmmm** [comment]
@xXWaterFrogzX ok thank you for the problem, we will try to fix

**Comment by HmmHmmmm** [comment]
@xXWaterFrogzX I've fixed, Can you use it?

**Comment by Adam1609** [comment]
Still not work. Form not showing, is there any virion I have to installed?

**Comment by HmmHmmmm** [comment]
download phar https://poggit.pmmp.io/ci/HmmHmmmm/ShopPlugin/ShopPlugin
It will install a virion

**Comment by HmmHmmmm** [comment]
@Adam1609 Download phar https://poggit.pmmp.io/ci/HmmHmmmm/ShopPlugin/ShopPlugin
It will install a virion

**Comment by Waater** [comment]
Yes it now works thank you very much :) @HmmHmmmm
